#!/bin/bash

path_run=$(dirname $0)

. ./inc/libui.sh

TITLE="UBLinux Installation"
.

. ./hooks/main.sh
i=0

while read line;
do
	hooks[$i]=$(echo $line | cut -d'|' -f1)
	(( i++ ))
	hooks[$i]=""
	(( i++ ))

done < "./hooks/info.txt"

hooks[$i]=Exit
(( i++ ))
hooks[$i]=""
i=0

while [ $i -lt 1 ]
do
	_dia_ask_option no "Base Menu" "\n\nPlease choose action." required "${hooks[@]}" || return 1
	answer=$ANSWER_OPTION

	if [ "$answer" != "Exit" ]; then

		hook=$(cat ./hooks/info.txt | grep "$answer" | cut -d'|' -f2)
		hook=${hook// }
		. "./hooks/$hook"
		i=0


	else
		rm *.txt
		i=1
	fi
done